export const chipListState = {
  positive: [
    "Hardworking",
    "Creative",
    "Team Player",
    "Leadership",
    "Innovative",
    "Problem Solver",
    "Detail-Oriented",
    "Reliable",
    "Responsible",
    "Adaptable",
    "Quick Learner",
    "Self-Motivated",
    "Collaborative",
    "Organized",
    "Efficient",
    "Communicative",
    "Proactive",
    "Supportive",
    "Analytical",
    "Focused",
    "Dedicated",
    "Goal-Oriented",
    "Strategic Thinker",
    "Positive Attitude",
    "Mentorship",
    "Ownership",
    "Time Management",
    "Critical Thinking",
    "Flexible",
    "Patient",
    "Empathetic",
    "Resilient",
    "Accountable",
    "Resourceful",
    "Tech-Savvy",
    "Customer-Oriented",
    "Decision Maker",
    "Innovative Thinker",
    "Consistent",
    "Disciplined",
    "Visionary",
    "Respectful",
    "Trustworthy",
    "Enthusiastic",
    "Supportive Leader",
    "Process-Oriented",
    "Execution Focused",
    "Quality Driven",
    "Clear Communicator",
    "Dependable",
  ],

  negative: [
    "Lazy",
    "Rude",
    "Impatient",
    "Arrogant",
    "Unreliable",
    "Disorganized",
    "Uncooperative",
    "Negative Attitude",
    "Poor Communication",
    "Lacks Initiative",
    "Careless",
    "Inconsistent",
    "Procrastinator",
    "Overconfident",
    "Defensive",
    "Micromanaging",
    "Irresponsible",
    "Unfocused",
    "Easily Distracted",
    "Unmotivated",
    "Rigid",
    "Resistant to Change",
    "Blames Others",
    "Poor Time Management",
    "Unprofessional",
    "Disrespectful",
    "Indecisive",
    "Unclear Communication",
    "Low Accountability",
    "Avoids Responsibility",
    "Lack of Ownership",
    "Short Tempered",
    "Overcritical",
    "Not Detail-Oriented",
    "Low Energy",
    "Unresponsive",
    "Poor Listener",
    "Inefficient",
    "Unstructured",
    "Passive",
    "Gossipy",
    "Unengaged",
    "Lacks Focus",
    "Overcomplicates",
    "Unprepared",
    "Dismissive",
    "Low Confidence",
    "Dependent",
    "Non-Collaborative",
    "Lacks Transparency",
  ],
};

export const Admins = [
  {
    email: "admin@gmail.com",
    password: "123",
    role: "admin",
    name: "Admin",
    id: "99",
    avatar: "https://i.pravatar.cc/200?img=1",
  },
];

export const Users = [
  {
    id: "1",
    name: "Jiwaji",
    email: "jiwaji@gmail.com",
    designation: "Software Engineer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=1",
    teammates: [],
    reviews: [],
  },
  {
    id: "2",
    name: "Vivek",
    email: "vivek@gmail.com",
    designation: "Product Manager",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=2",
    teammates: [],
    reviews: [],
  },
  {
    id: "3",
    name: "Ujjawal",
    email: "ujjawal@gmail.com",
    designation: "Intern",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=3",
    teammates: [],
    reviews: [],
  },
  {
    id: "4",
    name: "Guru",
    email: "guru@gmail.com",
    designation: "Lead",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=4",
    teammates: [],
    reviews: [],
  },
  {
    id: "5",
    name: "Anju",
    email: "anju@gmail.com",
    designation: "HR",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=5",
    teammates: [],
    reviews: [],
  },
  {
    id: "6",
    password: "123",
    name: "Kubendra",
    email: "kubendra@gmail.com",
    designation: "QA Engineer",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=51",
    teammates: [],
    reviews: [],
  },
  {
    id: "7",
    name: "Dinesh",
    email: "dinesh@gmail.com",
    designation: "DevOps Engineer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=7",
    teammates: [],
    reviews: [],
  },
  {
    id: "8",
    name: "Vikas",
    email: "vikas@gmail.com",
    designation: "Backend Developer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=8",
    teammates: [],
    reviews: [],
  },
  {
    id: "9",
    name: "Vishal",
    email: "vishal@gmail.com",
    designation: "Frontend Developer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=17",
    teammates: [],
    reviews: [],
  },
  {
    id: "10",
    name: "Vinay",
    email: "vinay@gmail.com",
    designation: "UI Designer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=18",
    teammates: [],
    reviews: [],
  },
  {
    id: "11",
    name: "Deep",
    email: "deep@gmail.com",
    designation: "Data Analyst",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=11",
    teammates: [],
    reviews: [],
  },
  {
    id: "12",
    name: "Kalpesh",
    email: "kalpesh@gmail.com",
    designation: "Support Engineer",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=12",
    teammates: [],
    reviews: [],
  },
  {
    id: "13",
    name: "Palak",
    email: "palak@gmail.com",
    designation: "Business Analyst",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=20",
    teammates: [],
    reviews: [],
  },
  {
    id: "14",
    name: "Raghav",
    email: "raghav@gmail.com",
    designation: "Tech Lead",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=14",
    teammates: [],
    reviews: [],
  },
  {
    id: "15",
    name: "Akhil",
    email: "akhil@gmail.com",
    designation: "Architect",
    password: "123",
    role: "user",
    avatar: "https://i.pravatar.cc/200?img=33",
    teammates: [],
    reviews: [],
  },
];
